#+ summary: Select only the art periods that have been assigned to artworks
#+ description: Select only the art periods that have been assigned to artworks
#+ endpoint: https://api.data.netwerkdigitaalerfgoed.nl/datasets/heritageflix/v1/services/v1/sparql
#+ tags:
#+   - Art Periods

PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?artPeriod
  (COUNT(?heritageObject) AS ?numberOfHeritageObjects)
  ?name
  ?startDate
  ?endDate
WHERE {
  ?heritageObject a schema:VisualArtwork ;
    schema:temporalCoverage ?artPeriod .
  ?artPeriod a schema:DefinedTerm ;
    schema:name ?name ;
    schema:startDate ?startDate .
  OPTIONAL { ?artPeriod schema:endDate ?endDate }
}
ORDER BY ?startDate
LIMIT 1000
