#+ summary: Select all heritage object belonging to a specific art period
#+ description: Select all heritage object belonging to a specific art period
#+ endpoint: https://api.data.netwerkdigitaalerfgoed.nl/datasets/heritageflix/v1/services/v1/sparql
#+ endpoint_in_url: False
#+ tags:
#+   - Heritage Objects
#+ defaults:
#+   - artPeriod: http://vocab.getty.edu/aat/300021147
#+ pagination: 50

PREFIX schema: <https://schema.org/>

SELECT *
WHERE {
  {
    SELECT *
    WHERE {
      ?heritageObject a schema:VisualArtwork ;
        schema:name ?name ;
        schema:dateCreated ?dateCreated ;
        schema:image/schema:contentUrl ?imageContentUrl ;
        schema:image/schema:encodingFormat ?imageEncodingFormat ;
        schema:image/schema:license ?imageLicense ; # TBD: also add name of the license?
        schema:creator/schema:name ?creatorName ;
        schema:temporalCoverage ?_artPeriod_iri .
    }
    ORDER BY ?dateCreated
  }
}
LIMIT 10000
